version: '3.8'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sql
      POSTGRES_DB: gorm
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6
    ports:
      - "6379:6379"

  app:
    build:
      context: .
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: sql
      DB_NAME: gorm
      REDIS_ADDR: redis:6379
    depends_on:
      - postgres
      - redis
    ports:
      - "8080:8080"

volumes:
  postgres_data:
